"""initial migration

Revision ID: 1e01cf894537
Revises: c006e8463eb4
Create Date: 2025-12-26 15:36:54.203919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e01cf894537'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
